config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'
  resources :subs do
    resources :topics 
  end

  scope 'topics/:topic_id', as: 'topic' do
    resources :comments, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  before_save :check_author

  def check_author
    if self.author.blank?
      self.author = 'Anon'
    end 
  end 
  
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :verify_paid

  def verify_paid
    #TODO fill this out
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic

  def new
    @comment = Comment.new
  end

  def create
    @comment = @topic.comments.new(comment_params)
    if @comment.save
      redirect_to sub_topic_path(@topic.sub_id, @topic.id)
    else
      render :new
    end
  end

  private

    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :update, :edit, :destroy]
  skip_before_action :verify_paid, only: :index
  after_action :more_cowbell

  def index
    @subs = Sub.all
  end

  def show
  end

  def new
    @sub = Sub.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @sub = Sub.new(sub_params)

    if @sub.save
      redirect_to sub_path(@sub)
    else
      render :new
    end
  end

  def update
    if @sub.update(sub_params)
      redirect_to sub_path(@sub)
    else
      render :edit
    end
  end

  def destroy
    @sub.destroy
    redirect_to subs_path
  end

  private
    def set_sub
      @sub = Sub.find(params[:id])
    end

    def sub_params
      params.require(:sub).permit(:name)
    end

    def more_cowbell
      Rails.logger.info "DING DING DING DING"
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_sub
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = @sub.topics
  end

  def show
  end

  def new
    @topic = @sub.topics.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @topic = @sub.topics.new(topic_params)
    if @topic.save
      redirect_to sub_topic_path(@sub, @topic)
    else
      render parital: "form"
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to [@sub, @topic]
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to sub_topics_path
  end

  private

    def topic_params
      params.require(:topic).permit(:name, :body)
    end

    def set_sub
      @sub = Sub.find(params[:sub_id])
    end
    
    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @sub.id ? 'Edit Sub' : 'Create Sub' %></h1>
<hr />
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/subs/edit.html.erb
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/subs/index.html.erb
<h1>Click a sub to view content</h1>
<%= link_to 'Create a new sub', new_sub_path %>
<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.name, sub %></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br />
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<br />
<%= link_to 'Delete Sub', @sub, method: :delete, data: { confirm: 'Really delete?' } %>

app/views/topics/_form.html.erb
<h1><%= @topic.id ? 'Edit Topic' : 'Create Topic' %></h1>
<hr />
<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Click a Topic To View Content</h1>
<%= link_to 'Create a new topic', new_sub_topic_path(@sub) %>
<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to topic.name, [@sub, topic] %></li>
  <% end %>
</ul>

app/views/topics/new.html.erb
<h1>Add a comment</h1>

<%= form_for [@topic, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>

  <br />
  
  <%= f.label :author %>
  <%= 
    f.text_field :author, 
    placeholder: 'Leave blank to remain anonymous' 
  %>

  <br />

  <%= f.submit %>
<% end %>```

app/views/topics/show.html.erb
<h1><%= @sub.name %> - <%= @topic.name %></h1>
<p><%= @topic.body %></p>

<% @topic.comments.each do |comment| %>
    <% render 'comments/comments', {comment: comment} %>
  <% end %>

<%= link_to 'Edit Topic', edit_sub_topic_path([@sub, @topic]) %>
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
<%= link_to 'Back To Topics', sub_topics_path(@sub) %>
<%= link_to 'Add Comment', new_topic_comment_path(@topic) %>